### ISSUE TITLE
Tidy up config file, especially confusing folder paths

### ISSUE THREAD

**Issue by cofiem** [QutEcoacoustics/baw-server#207]
This also applies to baw-workers. See also https://github.com/QutBioacoustics/baw-server/issues/156

**Comment by atruskie** [comment]
two potential renames:

analysis_jobs_results --> results from custom jobs
cached_analysis_results --> results stored in same format as other cached folders (2 char guid partitioned)

**Comment by cofiem** [comment]
Suggested changes to current folders:

 - analysis_results - *rename* to `custom_job_results` (to mirror the name we use for custom jobs)
 - analysis_runs - **delete** (AP.exe and working dirs will be local to worker VMs, not on QCIF storage)
 - analysis_scripts - **delete**
 - cached_analysis_jobs - *rename* to `cached_analysis_results`
 - cached_audio (no changes)
 - cached_datasets  - **delete**
 - cached_spectrograms (no changes)
 - original_audio (no changes)
 - harvester_to_do (no changes)

Changes to baw-worker paths:
````
paths:
    original_audios: (no change)
      - ./tmp/custom_temp_dir/_original_audio
    cached_spectrograms: (no change)
      - ./tmp/custom_temp_dir/_cached_spectrogram
    cached_audios: (no change)
      - ./tmp/custom_temp_dir/_cached_audio
    cached_datasets: **delete**
      - ./tmp/custom_temp_dir/_cached_dataset
    cached_analysis_jobs: *rename* to `cached_analysis_results`
      - ./tmp/custom_temp_dir/_cached_analysis_jobs
    worker_log_file: ./tmp/logs/worker.log  (no change)
    mailer_log_file: ./tmp/logs/mailer.log  (no change)
    audio_tools_log_file: ./tmp/logs/audio_tools.log  (no change)
    temp_dir: ./tmp/custom_temp_dir/temp (no change)
    working_dir: ./tmp/custom_temp_dir/working  (no change)
````

Changes to baw-server paths:
````
paths:
    image_magick_dir: <%= Rails.root %>/tmp/_image-magick **delete**
    original_audios: (no change)
      - <%= Rails.root %>/tmp/_original_audio
    cached_spectrograms: (no change)
      - <%= Rails.root %>/tmp/_cached_spectrogram
    cached_audios: (no change)
      - <%= Rails.root %>/tmp/_cached_audio
    analysis_scripts: **delete**
      - <%= Rails.root %>/tmp/_analysis_script
    analysis_results: *rename* to `custom_job_results`
      - <%= Rails.root %>/tmp/_analysis_result
    analysis_runs: **delete**
      - <%= Rails.root %>/tmp/_analysis_run
    cached_datasets: **delete**
      - <%= Rails.root %>/tmp/_cached_dataset
    cached_analysis_jobs: *rename* to `cached_analysis_results`
      - <%= Rails.root %>/tmp/_cached_analysis_jobs
    worker_log_file: <%= Rails.root %>/log/worker.<%= Rails.env %>.log (no change)
    mailer_log_file: <%= Rails.root %>/log/mailer.<%= Rails.env %>.log (no change)
    audio_tools_log_file: <%= Rails.root %>/log/audio_tools.<%= Rails.env %>.log (no change)
    temp_dir: <%= Rails.root %>/tmp (no change)
    working_dir: ./tmp/custom_temp_dir/working (no change)
````
