### ISSUE TITLE
Harvester instructions containing duplicate ids

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/baw-server#510]
The example config file for harvesting data from a site has duplicate user ids. This should be a simple fix:

Route: `/projects/:project_id/sites/:site_id/harvest.yml`

Current result:

```YAML
# the project
project_id: 1056

# the site
site_id: 2025

# this needs to be set manually
# below is a list of uploader_ids that have write access to this project
# uncomment the one that you want to set as the uploader of the audio files
# |---------- IMPORTANT: Ensure there is no whitespaces left before uploader_id
#uploader_id: 255 # Tshering Dema
#uploader_id: 88 # phil
#uploader_id: 93 # proe
#uploader_id: 112 # tarrantt
#uploader_id: 116 # towsey
#uploader_id: 164 # Liang
#uploader_id: 298 # kinley
#uploader_id: 340 # Sherub
#uploader_id: 374 # Gyeltshen
#uploader_id: 443 # Indra Prasad Acharja
#uploader_id: 531 # Wangchuk Dorji
#uploader_id: 532 # Indra Acharja
#uploader_id: 255 # Tshering Dema
#uploader_id: 255 # Tshering Dema

# this is the timezone for all the recordings.
# the value should be the timezone offset that
# the recorder was set to when it started recording.
# example: `utc_offset: '+10'` for Brisbane, Australia
utc_offset: 'INTENTIONALLY_INVALID'

# structured metadata to add to each recording.
# use this to record information about sensors, etc...
metadata:
#  sensor_type: SM2
#  notes:
#    - stripped left channel due to bad mic
#    - appears to have electronic interference from solar panel
```

Expected result:
```YAML
# the project
project_id: 1056

# the site
site_id: 2025

# this needs to be set manually
# below is a list of uploader_ids that have write access to this project
# uncomment the one that you want to set as the uploader of the audio files
# |---------- IMPORTANT: Ensure there is no whitespaces left before uploader_id
#uploader_id: 255 # Tshering Dema
#uploader_id: 88 # phil
#uploader_id: 93 # proe
#uploader_id: 112 # tarrantt
#uploader_id: 116 # towsey
#uploader_id: 164 # Liang
#uploader_id: 298 # kinley
#uploader_id: 340 # Sherub
#uploader_id: 374 # Gyeltshen
#uploader_id: 443 # Indra Prasad Acharja
#uploader_id: 531 # Wangchuk Dorji
#uploader_id: 532 # Indra Acharja

# this is the timezone for all the recordings.
# the value should be the timezone offset that
# the recorder was set to when it started recording.
# example: `utc_offset: '+10'` for Brisbane, Australia
utc_offset: 'INTENTIONALLY_INVALID'

# structured metadata to add to each recording.
# use this to record information about sensors, etc...
metadata:
#  sensor_type: SM2
#  notes:
#    - stripped left channel due to bad mic
#    - appears to have electronic interference from solar panel

```
